title: Pooja Krishnan # your name (or website title) here
logo: "/images/pooja krishnan (76 of 76).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master's from Technical University Munich
  <br><br>
  <a href="https://www.linkedin.com/in/pooja-krishnan-63a71050/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
